# Generated by Django 2.2.5 on 2019-10-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_product_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
