# Generated by Django 2.2.5 on 2019-10-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='up_count',
            field=models.IntegerField(default=0),
        ),
    ]
