# Generated by Django 2.2.5 on 2019-10-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_post_up_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='up_count',
            new_name='like_count',
        ),
    ]
